name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  formating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting with rustfmt
        run: cargo fmt --all -- --check

  validity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Check source is valid
        run: cargo check --workspace

  tests:
    runs-on: ubuntu-latest
    needs: validity
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --workspace --verbose

  clippy:
    runs-on: ubuntu-latest
    needs: validity
    steps:
      - uses: actions/checkout@v3
      - name: Lint code
        run: cargo clippy --workspace
